repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: pretty-format-json
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: black
    name: Run black code formatter
    description: This hook formats Python code.
    entry: env LC_ALL=C.UTF-8 black -q
    language: system
    args: [-l, "80"]
    types: [python]

  - id: clang-format
    name: clang-format
    description: Format files with ClangFormat.
    entry: clang-format
    language: system
    files: \.(c|cpp|h|hpp)$
    args: ['-fallback-style=none', '-i']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: flake8
    # note: ignores and excluded files in .flake8

- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--pre-summary-newline, --in-place]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    args:
    # Match industrial_ci list
    - --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D203,D212,D404
