int32 mode
int32 PROBING_DISABLED=0
int32 PROBE_EXPECT_RISING_EDGE=1 # Expect a rising edge, error if probe is active at start
int32 PROBE_EXPECT_FALLING_EDGE=2 # Expect a falling edge, error if probe is inactive at start
int32 PROBE_RETRACT=3 # Error if a rising edge is seen, ignore a falling edge and keep going
---
string message
bool success
