int32 mode
int32 PROBE_NONE=0
# Follow LinuxCNC G38.x codes here
int32 PROBE_REQUIRE_RISING_EDGE=2 # Capture a rising edge and stop, error if probe is active at start
int32 PROBE_OPTIONAL_RISING_EDGE=3 # Capture a rising edge and stop
int32 PROBE_REQUIRE_FALLING_EDGE=4 # Expect a falling edge, error if probe is inactive at start
int32 PROBE_OPTIONAL_FALLING_EDGE=5 # Error if a rising edge is seen, ignore a falling edge and keep going
int32 PROBE_IGNORE_INPUT=6 # Ignore all probe inputs regardless of direction
---
