# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Formatting (pre-commit)

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Install black
        run: sudo -H pip3 install black
      - uses: pre-commit/action@v3.0.0
        id: precommit
      - name: Upload pre-commit changes
        if: failure() && steps.precommit.outcome == 'failure'
        uses: rhaschke/upload-git-patch-action@main
        with:
          name: pre-commit
